Fix assembla web hook failure (#27)
* Fix reporting on PoCheck status

Error was:
poChecker.py, line 238
    print c.getReport().encode(UTF-8) + nn
          ^
SyntaxError: invalid syntax

Concatenation of bytes and str

* Include CGI webhook in repo

When updating to Python3 the cgi/webhook file was missed.
Including it in this repository so that it can not be missed in future.

The webhook file is kept up to date with crontab.